apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://git-server.gitops.svc.cluster.local/repo.git
    targetRevision: main
    path: gitops
    directory:
      recurse: false
      exclude: 'root-application.yaml,ephemeral-pr-applicationset.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
